language: elixir
elixir:
  - 1.7.0
otp_release:
  - 21.0

services:
  - postgresql

addons:
  postgresql: "9.6"

script:
  - "mix compile --warnings-as-errors --force"
  - "mix format --check-formatted"
  - "mix test"
  - "mix credo --strict"
  - "travis_wait 30 mix dialyzer --halt-exit-status"
  - "mix coveralls.travis"
